name: moments
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.1.beta

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8

  # Backend & Data
  supabase_flutter: ^2.10.3
  google_sign_in: ^6.2.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_ai: ^3.7.0
  firebase_auth: ^6.1.4
  flutter_local_notifications: ^17.2.1
  moments_native:
    path: ./plugins/moments_native

  # Maps & Location
  location: ^5.0.3
  geocoding: ^3.0.0
  mapbox_maps_flutter: ^2.21.1
  supercluster: ^3.2.0

  # UI Components
  carousel_slider: ^5.0.0

  # Image handling
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  http: ^1.2.0
  path_provider: ^2.1.4

  # Animations
  flutter_animate: ^4.5.0
  motor: ^1.0.1
  animations: ^2.1.0
  lottie: ^3.3.2
  dotlottie_loader: ^0.0.4

  # UI & Fonts
  google_fonts: ^6.2.1
  hugeicons: ^1.1.1
  flutter_svg: ^2.2.2

  # Navigation
  go_router: ^14.1.4
  flutter_floating_bottom_bar: ^1.3.0

  # State Management
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Environment
  flutter_dotenv: ^5.1.0

  # Utilities
  equatable: ^2.0.5
  uuid: ^4.4.0
  latlong2: ^0.9.1
  image_picker_platform_interface: ^2.11.1
  avatar_stack: ^3.0.0
  share_plus: ^10.1.2
  flutter_image_compress: ^2.4.0
  flutter_screenutil: ^5.9.3
  giphy_get : any

  # Audio & Voice Notes
  just_audio: ^0.9.40
  record: ^6.1.2
  permission_handler: ^11.3.0
  path: ^1.9.1
  video_player: ^2.10.1
  wechat_assets_picker: ^10.0.0
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.31
  connectivity_plus: ^7.0.0
  video_compress: ^3.1.3
  chewie: ^1.13.0

  # Material3 Expressive
  button_m3e: ^0.1.2
  icon_button_m3e: ^0.2.1
  progress_indicator_m3e: ^0.1.1
  quick_actions: ^1.1.0
  logger: ^2.6.2
  shared_preferences: ^2.5.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_m3shapes_extended: ^1.0.0
  flutter_blurhash: ^0.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  flutter_contacts: ^1.1.9+2
  pull_down_button: ^0.10.2
  intl_phone_field: ^3.2.0
  powersync: ^1.18.0
  chat_bubbles: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  drift_dev: ^2.26.0
  build_runner: ^2.10.4
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/svg/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/GoogleSansFlex.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
